spring:
  application:
    name: spring-tricount

  profiles:
    active: local

  # H2 DataBase
  datasource:
    url: jdbc:h2:tcp://localhost/~/tricount
    username: sa
    password:

  # JPA
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Redis
  redis:
    host: localhost
    port: 6379

# Security - OAuth2
security:
  oauth2:
    client:

      # Kakao Provider
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

      # Kakao Registration
      registration:
        kakao:
          client-id: c2ebef906e5e1908b1ac4ab5bd1c961b
          client-secret: ic9XSU2hplPY5H8XkfG6xwUDlWJP3gLL
          client-authentication-method: client_secret_post
          redirect-uri: https://localhost:8080/login/oauth2/code/kakao
          authorization-grant-type: authorization_code
          client-name: kakao
          scope:
            - profile_nickname
            - profile_image
            - account_email

# Security - JWT
jwt:
  secret: 16a913d84682cda222300433e04d6ecc48af40b7f10300a4909dfe27bee8d540
