spring:
  application:
    name: spring-tricount

  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/tricount
    username: sa
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: localhost
    port: 6379

jwt:
  secret: 16a913d84682cda222300433e04d6ecc48af40b7f10300a4909dfe27bee8d540