spring:
  application:
    name: spring-tricount

  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/tricount
    username: sa
    password:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          kakao:
            client-id: 1065528
            client-secret: ic9XSU2hplPY5H8XkfG6xwUDlWJP3gLL
            client-authentication-method: client_secret_post
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

jwt:
  secret: 16a913d84682cda222300433e04d6ecc48af40b7f10300a4909dfe27bee8d540